package org.next.lms.message.domain;

public enum MessageType {
    USER_LIKE_CONTENT,
    USER_LIKE_REPLY,
    NEW_CONTENT_CREATED,

    LECTURE_ENROLL_REQUEST,
    LECTURE_ENROLL_APPROVED,
    LECTURE_ENROLL_REJECT,
    LECTURE_ENROLLED

}
