INSERT INTO AUTHORITY VALUES(1, 'ROLE_BANNED');
INSERT INTO AUTHORITY VALUES(2, 'ROLE_NOT_AUTHORIZED');
INSERT INTO AUTHORITY VALUES(3, 'ROLE_STUDENT');
INSERT INTO AUTHORITY VALUES(4, 'ROLE_TEACHING_ASSISTANT');
INSERT INTO AUTHORITY VALUES(5, 'ROLE_PROFESSOR');
INSERT INTO AUTHORITY VALUES(6, 'ROLE_SYSTEM_MANAGER');